services:
  postgres:
    image: postgres:17-alpine
    container_name: biolynq_postgres_prod
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-biolynq_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-biolynq_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: biolynq_redis_prod
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_prod_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: ${DOCKER_USER:-vivek6201}/biolynq-server:${TAG:-latest}
    container_name: biolynq_server_prod
    restart: always
    ports:
      - "${PORT:-8000}:8000"
    env_file: .env
    environment:
      - DB_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-biolynq_db}?sslmode=disable
      - REDIS_URL=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    image: ${DOCKER_USER:-vivek6201}/biolynq-worker:${TAG:-latest}
    container_name: biolynq_worker_prod
    restart: always
    env_file: .env
    environment:
      - DB_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-biolynq_db}?sslmode=disable
      - REDIS_URL=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_prod_data:
  redis_prod_data:
