services:
  redis:
    image: redis:7-alpine
    container_name: biolynq_redis_prod
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_prod_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: ${DOCKER_USER:-vivek6201}/biolynq-server:${TAG:-latest}
    container_name: biolynq_server_prod
    restart: always
    ports:
      - "${PORT:-8000}:8000"
    env_file: .env
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      redis:
        condition: service_healthy

  worker:
    image: ${DOCKER_USER:-vivek6201}/biolynq-worker:${TAG:-latest}
    container_name: biolynq_worker_prod
    restart: always
    env_file: .env
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_prod_data:
